name: scion-environment
channels:
  - conda-forge
dependencies
  - matplotlib==3.1.1
  - numpy==1.16.5
  - pandas==0.25.1
  - seaborn==0.9.0
  - scikit-learn==0.21.3
  - bmdcluster==0.3.1
  - rdkit==2020.03.2