name: scion-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - rdkit
  - pip
  - pip:
    - bmdcluster
    - matplotlib
    - pandas
    - seaborn
    - scikit-learn
    - molmass
    - xlrd